language: node_js
sudo: required
node_js:
  - 10
  - 8
  - 6
before_install:
  - sudo sysctl fs.inotify.max_user_watches=524288
install: 'yarn install --ignore-engines'
script:
  # Test source (with cross-package coverage)
  - yarn link-entries src
  - yarn flow
  - yarn lint
  - yarn test:unit --maxWorkers=2
  # Test build
  - yarn build
  - yarn link-entries dist
  - yarn start & yarn test:e2e
after_success:
  # Report coverage
  - yarn codecov
cache:
  yarn: true
  directories:
    - /home/travis/.cypress/Cypress
